export default {
    'ai-cheatsheet':       'AI',
    'ansible-cheatsheet':  'Ansible',
    'aws-cheatsheet':      'AWS',
    'azure-cheatsheet':    'Azure',
    'bash-cheatsheet':     'Bash',
    'containers-cheatsheet': 'Containers',
    'dotnet-cheatsheet':   '.NET',
    'git-cheatsheet':      'Git',
    'go-cheatsheet':       'Go',
    'kql-cheatsheet':      'KQL',
    'linux-cheatsheet':    'Linux',
    'nginx-cheatsheet':    'Nginx',
    'powershell-cheatsheet': 'PowerShell',
    'python-cheatsheet':   'Python',
    'security-cheatsheet': 'Security',
    terraform:             'Terraform',
    'typescript-cheatsheet': 'TypeScript',
    'windows-cheatsheet':  'Windows',
}
