title: "Libre DevOps"
email: libredevops@craigthacker.dev
description: >- # this means to ignore newlines until "baseurl:"
  A site for free and open source DevOps tooling
baseurl: "/"
url: "https://libredevops.org"
github_username:  freelibredevops

logo: /assets/img/libredevops.png
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
permalink: pretty

footer_content: >-
  <li class="list-inline-item">
      <a href="https://hub.docker.com/u/libredevops" title="Docker Hub">
        <span class="fa-stack fa-lg" aria-hidden="true">
          <i class="fas fa-circle fa-stack-2x"></i>
          <i class="fab fa-docker fa-stack-1x fa-inverse"></i>
        </span>
        <span class="sr-only">Docker Hub</span>
     </a>
    </li>
  <li class="list-inline-item">
    <a href="https://registry.terraform.io/namespaces/libre-devops" title="Terraform Registry">
      <span class="fa-stack fa-lg" aria-hidden="true">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fas fa-code fa-stack-1x fa-inverse"></i>
      </span>
      <span class="sr-only">Terraform Registry</span>
   </a>
  </li>
  <li class="list-inline-item">
      <a href="https://keybase.io/team/libredevops" title="Keybase">
        <span class="fa-stack fa-lg" aria-hidden="true">
          <i class="fas fa-circle fa-stack-2x"></i>
          <i class="fab fa-keybase fa-stack-1x fa-inverse"></i>
        </span>
        <span class="sr-only">Keybase</span>
     </a>
    </li>
  <li class="list-inline-item">
      <a href="https://github.com/libre-devops" title="GitHub">
        <span class="fa-stack fa-lg" aria-hidden="true">
          <i class="fas fa-circle fa-stack-2x"></i>
          <i class="fab fa-github fa-stack-1x fa-inverse"></i>
        </span>
        <span class="sr-only">GitHub</span>
     </a>
  </li>


aux_links:
  "View on GitHub":
    - "https://github.com/libre-devops/libredevops-dot-org"

back_to_top: true
back_to_top_text: "Back to top"

#theme: just-the-docs
remote_theme: "just-the-docs/just-the-docs"
color_scheme: "dark"
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
