title: "Libre DevOps"
email: libredevops@craigthacker.dev
description: >- # this means to ignore newlines until "baseurl:"
  A site for free and open source DevOps tooling
baseurl: "/"
url: "https://libredevops.org"
github_username:  freelibredevops

logo: /assets/img/favicon.ico
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true

footer_content: >-
  terraform-compliance made with <span style=\"color: #e25555;\">&hearts;</span>.
  Distributed by an <a href=\"https://tldrlegal.com/license/mit-license\">MIT license</a>.


aux_links:
  "GitHub Org Page":
    - "github.com/libre-devops"
#  "Edit this Page":
#    - "{{site.github.repository_url}}/tree/master/docs/{{page.path}}"

#theme: just-the-docs
remote_theme: "just-the-docs/just-the-docs"

plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
