version: "3.7"

services:
  jekyll:
    build:
      context: ./
    ports:
      - 8080:4000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t

