source "https://rubygems.org" # source "https://gems.ruby-china.com"

gemspec

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
    gem 'jekyll-remote-include', :github => 'netrics/jekyll-remote-include'
end
