source "https://rubygems.org" # source "https://gems.ruby-china.com"

gemspec

group :jekyll_plugins do
gem "github-pages",
gem 'jekyll-remote-include', :github => 'netrics/jekyll-remote-include'
end

gem "jemoji"
